# Generated by Django 4.1.3 on 2022-11-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postit_api', '0002_alter_post_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creatade_at',
            new_name='created_at',
        ),
    ]
